name: Build
on:
  push:
    branches:
      - main

env:
  GH_TOKEN: ${{ secrets.GH_TOKEN }}

jobs:
  build-vite:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version-file: .nvmrc
      - uses: oven-sh/setup-bun@v2
        with:
          bun-version-file: package.json
      - name: Install dependencies
        run: bun install --frozen-lockfile
      - name: Test
        run: bun run test
      - name: Build Vite
        run: bun run --cwd vite build
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: vite
          path: vite/dist
          retention-days: 1

  release-macos:
    needs: build-vite
    runs-on: macos-latest
    env:
      CSC_KEY_PASSWORD: ${{ secrets.CSC_KEY_PASSWORD }}
      CSC_LINK: ${{ secrets.CSC_LINK }}
      APPLEID: ${{ secrets.APPLEID }}
      APPLEIDPASS: ${{ secrets.APPLEIDPASS }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version-file: .nvmrc
      - uses: oven-sh/setup-bun@v2
        with:
          bun-version-file: package.json
      - name: Install dependencies
        run: bun install --frozen-lockfile
      - name: Download built Vite files
        uses: actions/download-artifact@v4
        with:
          name: vite
          path: server/build
      - name: Build app
        run: bun run --cwd server release -p always

  release-windows:
    needs: build-vite
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version-file: .nvmrc
      - uses: oven-sh/setup-bun@v2
        with:
          bun-version-file: package.json
      - name: Install dependencies
        run: bun install --frozen-lockfile
      - name: Download built Vite files
        uses: actions/download-artifact@v4
        with:
          name: vite
          path: server/build
      - name: Build app
        run: bun run --cwd server release --win -p always

  release-linux:
    needs: build-vite
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version-file: .nvmrc
      - uses: oven-sh/setup-bun@v2
        with:
          bun-version-file: package.json
      - name: Install dependencies
        run: bun install --frozen-lockfile
      - name: Download built Vite files
        uses: actions/download-artifact@v4
        with:
          name: vite
          path: server/build
      - name: Build app
        run: bun run --cwd server release --linux -p always
